"""Correcting to allow for null values

Revision ID: 306514726dae
Revises: 3fa10eef0f1e
Create Date: 2026-02-28 21:52:14.251978

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "306514726dae"
down_revision = "3fa10eef0f1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sponsors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_classification", sa.String(length=20), nullable=True
            )
        )
        batch_op.alter_column(
            "first_donation_year", existing_type=sa.VARCHAR(length=4), nullable=True
        )
        batch_op.drop_column("organization_classificaiton")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sponsors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_classificaiton", sa.VARCHAR(length=20), nullable=False
            )
        )
        batch_op.alter_column(
            "first_donation_year", existing_type=sa.VARCHAR(length=4), nullable=False
        )
        batch_op.drop_column("organization_classification")

    # ### end Alembic commands ###
