"""Fixing bad mapping again

Revision ID: 3fa10eef0f1e
Revises: d1eb4b938582
Create Date: 2026-02-28 21:32:52.535547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa10eef0f1e'
down_revision = 'd1eb4b938582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_sponsor_id'), ['sponsor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_sponsor_id'))

    # ### end Alembic commands ###
