"""Fixing bad mapping

Revision ID: d1eb4b938582
Revises: db6e77706912
Create Date: 2026-02-28 21:30:34.313405

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1eb4b938582"
down_revision = "db6e77706912"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.alter_column("sponsor_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_index(batch_op.f("ix_bills_sponsor_id"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bills_sponsor_id"), ["sponsor_id"], unique=False
        )
        batch_op.alter_column("sponsor_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
