"""Add model tables

Revision ID: db6e77706912
Revises:
Create Date: 2026-02-28 21:18:50.863072

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db6e77706912"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("organization_classificaiton", sa.String(length=20), nullable=False),
        sa.Column("donation_count_all", sa.Integer(), nullable=True),
        sa.Column("donation_count_L3", sa.Integer(), nullable=True),
        sa.Column("total_all", sa.Float(), nullable=True),
        sa.Column("total_L3", sa.Float(), nullable=True),
        sa.Column("pct_c_above_all", sa.Float(), nullable=True),
        sa.Column("pct_c_above_L3", sa.Float(), nullable=True),
        sa.Column("avg_donation_all", sa.Float(), nullable=True),
        sa.Column("avg_donation_L3", sa.Float(), nullable=True),
        sa.Column("amt_allcond_all", sa.Float(), nullable=True),
        sa.Column("amt_allcond_L3", sa.Float(), nullable=True),
        sa.Column("pct_c_allcond_all", sa.Float(), nullable=True),
        sa.Column("pct_c_allcond_L3", sa.Float(), nullable=True),
        sa.Column("pct_c_IL_all", sa.Float(), nullable=True),
        sa.Column("pct_c_IL_L3", sa.Float(), nullable=True),
        sa.Column("num_bills", sa.Integer(), nullable=True),
        sa.Column("pct_bills_passed", sa.Float(), nullable=True),
        sa.Column("first_donation_year", sa.String(length=4), nullable=False),
        sa.Column("effectiveness_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=20), nullable=False),
        sa.Column("session_identifier", sa.String(length=20), nullable=True),
        sa.Column("organization_classification", sa.String(length=20), nullable=True),
        sa.Column("first_action", sa.Date(), nullable=True),
        sa.Column("num_sponsors", sa.Integer(), nullable=True),
        sa.Column("became_law", sa.Boolean(), nullable=True),
        sa.Column("referred_to_committee", sa.Boolean(), nullable=True),
        sa.Column("committee_passages", sa.Integer(), nullable=True),
        sa.Column("passed_first_chamber", sa.Boolean(), nullable=True),
        sa.Column("passed_full_legislature", sa.Boolean(), nullable=True),
        sa.Column("sponsor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sponsor_id"],
            ["sponsors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bills_sponsor_id"), ["sponsor_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bills_sponsor_id"))

    op.drop_table("bills")
    op.drop_table("sponsors")
    # ### end Alembic commands ###
